export const projectTypes = [
  "Startup",
  "Freelance",
  "Open Source",
  "College Project",
  "Hackathon",
  "Content Creation",
];

export const projectStatuses = ["Open", "In Progress", "Closed"];

export const applicationStatuses = ["Pending", "Accepted", "Rejected"];

export const experienceLevels = ["Beginner", "Intermediate", "Advanced", "Professional"];

export const allSkills = [
  "React",
  "JavaScript",
  "TypeScript",
  "HTML",
  "CSS",
  "Tailwind CSS",
  "Node.js",
  "Express.js",
  "Firebase",
  "Firestore",
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "Python",
  "Django",
  "Flask",
  "Java",
  "Kotlin",
  "Flutter",
  "React Native",
  "Android",
  "iOS",
  "UI Design",
  "UX Design",
  "Figma",
  "Canva",
  "Photoshop",
  "Illustrator",
  "Video Editing",
  "Motion Design",
  "After Effects",
  "Premiere Pro",
  "Content Writing",
  "Copywriting",
  "SEO",
  "Marketing",
  "Social Media",
  "Branding",
  "Product Design",
  "Product Management",
  "GitHub",
  "Git",
  "API Integration",
  "REST API",
  "AI",
  "GenAI",
  "ChatGPT API",
  "Machine Learning",
  "Data Analysis",
  "Cybersecurity",
  "Cloud",
  "AWS",
  "Vercel",
  "Netlify",
  "Game Development",
  "Unreal Engine",
  "Unity",
  "Blender",
  "3D Modeling",
];

export const popularSkills = allSkills;
